# Generated by Django 4.2.6 on 2023-11-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.FloatField(default=0.0, help_text='million on US dollars', verbose_name='Budget'),
        ),
    ]
