# Generated by Django 4.2.6 on 2023-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default.png', upload_to='movies/', verbose_name='Poster'),
        ),
    ]
